server:
  port: 1017
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: oj
  username: root
  password: root
  charset: utf8mb4
  loc: Asia/Shanghai
redis:
  host: 127.0.0.1
  port: 6379
  password: xp918896
rabbitmq:
  username: MGAronya
  password: MGAronya
  host: 127.0.0.1
  port: 5672
  virtual: MGAronya
search:
  subscriptionKey1: 542a1ee0e65545569e18c1809d3c8b1d
  subscriptionKey2: 0da978c807204ce8af37ff009d37019b
translation:
  subscriptionKey1: dae59c6b1cc44727a90b6e0ea1a65b89
  subscriptionKey2: ee6a35f0d009403fb99d34bb9ec616c3
poj:
  user: 20jzhang
  password: xp918896
hdu:
  user: StarCrusader
  password: Xp918896
spoj:
  user: mgaronya
  password: xp918896
cf:
  user: mgaronya
  password: xp918896
atcoder:
  user: mgaronya
  password: xp918896
uva:
  user: mgaronya
  password: xp918896
uoj:
  user: mgaronya
  password: xp918896
ural:
  user: mgaronya
  password: 363718WA
hackerrank:
  user: 20jzhang@stu.edu.cn
  password: xp918896
docker:
  id: test1
  type: test
  postmap: 3000:3000
  cpu: 0,1
chatgpt:
  url: https://api.openai-proxy.org/v1/chat/completions
  apikey: sk-UW23o17SPPUKcA51yXVegofesyWzNg3x7C0EsSWVIzetoV0L
  