server:
  port: 1017
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: oj
  username: root
  password: xp918896
  charset: utf8
  loc: Asia/Shanghai
redis:
  host: 127.0.0.1
  port: 6379
  password: xp918896
rabbitmq:
  username: MGAronya
  password: MGAronya
  host: 127.0.0.1
  port: 5672
  virtual: MGAronya
search:
  subscriptionKey: 9049f3e221324fac89a201405cbb4c54
  endpoint: https://api.bing.microsoft.com/v7.0/search