server:
  port: 1017
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: oj
  username: root
  password: root
  addredis: 6379
  redispass: 
  charset: utf8
  loc: Asia/Shanghai