server:
  port: 1017
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: oj
  username: root
  password: xp918896
  charset: utf8
  loc: Asia/Shanghai
redis:
  host: 127.0.0.1
  port: 6379
  password: xp918896
rabbitmq:
  username: MGAronya
  password: MGAronya
  host: 127.0.0.1
  port: 5672
  virtual: MGAronya
search:
  subscriptionKey1: 9049f3e221324fac89a201405cbb4c54
  subscriptionKey2: 4c557556cc434a6ab5c9ae5939022015
poj:
  user: 20jzhang
  password: xp918896
hdu:
  user: StarCrusader
  password: Xp918896
spoj:
  user: mgaronya
  password: xp918896
cf:
  user: mgaronya
  password: xp918896